### PR TITLE
Adding websockets to kansas-comet

### PR DESCRIPTION
**Pull request by moizjv**
- Added websockets to kansas-comet
- Added socketConnection object to Document
- socketApplication method to complete handshake from client browser
- receiveEvents to will handle socket connection which is open between client and server
- kansas-comet.js to initiate a websocket connection if browser is capable of establishing websocket else fall-   back on long polling method
- Some formatting changes to kansas-comet.js
- Added additional libraries to cabal
- Dr. @andygill please review :)

### CODE REVIEW

**Comment by RyanGlScott** [comment]
This looks interesting, but I'm not quite sure how an end-user (e.g., `blank-canvas`) would make use of the `socketApplication` function. Can you give an example of how it's used?

Also, if I'm reading the code right, it looks like the `Document` doesn't use a websocket by default. What must be done to enable normal `kansas-comet` use via a websocket?

**Comment by RyanGlScott** [comment]
Also, I tested this recently with `blank-canvas`, and I noticed that refreshing the browser repeatedly while running with this version `kansas-comet` causes a huge amount of lag. I'm not sure what's causing that, but we definitely don't want to push through those changes while that bug's present.

**Comment by moizjv** [comment]
Hi Ryan, 
Can you take a look at https://github.com/moizjv/blank-canvas/tree/websockets branch where i have used websockets enabled kansas-comet in blank canvas. Also what is the browser and operating system that you tested on, i would like to reproduce that if that is happening, it works fine on mac and google chrome.

**Comment by RyanGlScott** [comment]
My bad, I didn't see that repo (I probably should have realized that `blank-canvas` would have needed to be changed). Now that I've installed that, it works beautifully, and the bug went away too!

In that case, everything looks good. Can you also make a pull request for `blank-canvas` as well?

**Comment by moizjv** [comment]
Yes, `blank-canvas` depends on `kansas-comet` to be updated so once we merge this and bump the version, I will test it and raise a request in `blank-canvas`

**Comment by RyanGlScott** [comment]
Go ahead and make a pull request anyway. I was wanting to post some `blank-canvas`-specific feedback. For example, the [benchmark suite](https://github.com/ku-fpg/blank-canvas-mark) doesn't work properly with the websockets branch of `blank-canvas` on Firefox on Linux for me.

**Comment by moizjv** [comment]
I have made the pull request in blank-canvas too, but that depends on updated version of `kansas-comet` please double check .cabal files too. Can you test once on chrome and benchmark suite too. Thank you for looking into this. :+1:

**Comment by andygill** [comment]
Pulled. Thanks!

**Pull request closed without merging**
